New n3-utils and error-utils updater libraries
rdf-pipeline/noflo-rdf-components pull request #211
Opened 2017-02-24 09:51 UTC by glenna-m

2017-02-24 18:14 UTC, dbooth-boston commented on components/lib/n3-utils.js
> + * @return a promise to return the N3 store converted to JSON-LD format or a reject on error
Suggest rewording this: @return a promise to return either the JSON-LD format or a reject on error

2017-02-24 18:15 UTC, dbooth-boston commented on components/lib/n3-utils.js
> + * @return a promise to return the N3 store converted to JSON-LD format or a reject on error
Suggest rewording this to: @return a promise to return either the resulting JSON-LD or a reject on error

2017-02-24 18:20 UTC, dbooth-boston commented on components/lib/n3-utils.js
> +
Small stylistic request: I prefer having no blank line after the function header.  (To my eyes it helps keep the function together and it helps make the code fit in the visible window on the screen.)  If you think it is better to have one then let's take a poll of our developers to determine a preference.  It is not covered in the google style guide.

2017-02-24 18:22 UTC, dbooth-boston requested changes
LGTM subject to very minor comments.  No need for re-review.

2017-03-17 22:45 UTC, dbooth-boston approved these changes
LGTM

2017-03-20 13:58 UTC, dmtaub commented on components/lib/n3-utils.js
> +                    }, {'@default': []}), {})
took me a moment to realize that {} was a second argument to a function above...

2017-03-20 14:07 UTC, dmtaub commented on test/data/cmumps-patient7.jsonld
> -                "label": "BUNNY, BUGS"
Remind me: is this because the test output didn't match the test input?

2017-03-20 14:07 UTC, dmtaub commented on test/error-utils-mocha.js
> +// error-utils-mocha.js
Yay tests!

2017-03-20 14:08 UTC, dmtaub commented
LGTM

2017-03-30 20:38 UTC, closed without merging